package com.expenseintelligence.report;
import com.expenseintelligence.entity.Expense;
import com.expenseintelligence.repository.ExpenseRepository;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.*;
import org.springframework.stereotype.Service;
import java.io.ByteArrayOutputStream;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.UUID;

@Service @RequiredArgsConstructor @Slf4j
public class ReportService {
    private final ExpenseRepository expenseRepository;
    private static final DateTimeFormatter FMT = DateTimeFormatter.ofPattern("MMM dd, yyyy");
    private static final DeviceRgb BLUE = new DeviceRgb(59,130,246);
    private static final DeviceRgb LGRAY = new DeviceRgb(248,250,252);
    private static final DeviceRgb DARK = new DeviceRgb(15,23,42);

    public byte[] generatePdfReport(UUID userId, LocalDate start, LocalDate end) {
        List<Expense> expenses = expenseRepository.findByUserIdAndDateRange(userId,start,end);
        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            PdfDocument pdf = new PdfDocument(new PdfWriter(baos));
            Document doc = new Document(pdf, PageSize.A4);
            doc.setMargins(40,40,40,40);
            // Header
            Table hdr = new Table(UnitValue.createPercentArray(new float[]{70,30})).useAllAvailableWidth();
            hdr.addCell(new Cell().add(new Paragraph("Expense Intelligence").setFontSize(22).setBold().setFontColor(new DeviceRgb(255,255,255)))
                .add(new Paragraph(start.format(FMT)+" – "+end.format(FMT)).setFontSize(10).setFontColor(new DeviceRgb(186,230,253)))
                .setBackgroundColor(BLUE).setPadding(20).setBorder(null));
            hdr.addCell(new Cell().add(new Paragraph("Financial Report").setFontSize(13).setFontColor(new DeviceRgb(255,255,255)).setTextAlignment(TextAlignment.RIGHT))
                .setBackgroundColor(BLUE).setPaddingRight(20).setPaddingTop(20).setBorder(null));
            doc.add(hdr); doc.add(new Paragraph("\n"));
            // Summary
            BigDecimal total = expenses.stream().map(Expense::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add);
            Table sumTbl = new Table(UnitValue.createPercentArray(new float[]{50,50})).useAllAvailableWidth();
            addSumCard(sumTbl,"Total Expenses","$"+String.format("%.2f",total));
            addSumCard(sumTbl,"Transactions",String.valueOf(expenses.size()));
            doc.add(sumTbl); doc.add(new Paragraph("\n"));
            // Data table
            doc.add(new Paragraph("Transactions").setFontSize(14).setBold().setFontColor(DARK).setMarginBottom(8));
            Table tbl = new Table(UnitValue.createPercentArray(new float[]{30,15,20,15,20})).useAllAvailableWidth();
            for (String h : new String[]{"Description","Date","Category","Payment","Amount"})
                tbl.addHeaderCell(new Cell().add(new Paragraph(h).setBold().setFontColor(ColorConstants.WHITE)).setBackgroundColor(BLUE).setPadding(10).setBorder(null));
            boolean alt = false;
            for (Expense e : expenses) {
                DeviceRgb bg = alt ? LGRAY : new DeviceRgb(255,255,255);
                String cat = e.getCategory()!=null?e.getCategory().getName():e.getAiCategory()!=null?e.getAiCategory()+" (AI)":"—";
                addTd(tbl,e.getTitle(),bg); addTd(tbl,e.getExpenseDate().format(FMT),bg); addTd(tbl,cat,bg);
                addTd(tbl,e.getPaymentMethod()!=null?e.getPaymentMethod().name():"—",bg);
                tbl.addCell(new Cell().add(new Paragraph("$"+String.format("%.2f",e.getAmount())).setBold().setFontColor(DARK))
                    .setBackgroundColor(bg).setPadding(8).setBorder(null).setTextAlignment(TextAlignment.RIGHT));
                alt=!alt;
            }
            doc.add(tbl);
            doc.add(new Paragraph("\nGenerated by Expense Intelligence · "+LocalDate.now().format(FMT)).setFontSize(9).setFontColor(new DeviceRgb(148,163,184)).setTextAlignment(TextAlignment.CENTER));
            doc.close();
            return baos.toByteArray();
        } catch (Exception e) { log.error("PDF failed",e); throw new RuntimeException("PDF generation failed",e); }
    }

    private void addSumCard(Table t, String label, String value) {
        t.addCell(new Cell().add(new Paragraph(label).setFontSize(10).setFontColor(new DeviceRgb(100,116,139)))
            .add(new Paragraph(value).setFontSize(18).setBold().setFontColor(DARK))
            .setBackgroundColor(LGRAY).setPadding(15).setMargin(5).setBorderRadius(new com.itextpdf.layout.properties.BorderRadius(8)));
    }
    private void addTd(Table t, String text, DeviceRgb bg) {
        t.addCell(new Cell().add(new Paragraph(text!=null?text:"—").setFontSize(10)).setBackgroundColor(bg).setPadding(8).setBorder(null));
    }

    public byte[] generateExcelReport(UUID userId, LocalDate start, LocalDate end) {
        List<Expense> expenses = expenseRepository.findByUserIdAndDateRange(userId,start,end);
        try (XSSFWorkbook wb = new XSSFWorkbook(); ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            XSSFSheet sheet = wb.createSheet("Expenses");
            int[] widths = {8000,4000,5000,5000,4000,4000,4500,6000};
            for (int i=0;i<widths.length;i++) sheet.setColumnWidth(i,widths[i]);
            CellStyle hStyle = headerStyle(wb), curStyle = currencyStyle(wb);
            CellStyle altStyle = altRowStyle(wb), normStyle = wb.createCellStyle(), totalStyle = totalStyle(wb), totalCurr = totalCurrStyle(wb);
            int row = 0;
            Row titleRow = sheet.createRow(row++);
            org.apache.poi.ss.usermodel.Cell tc = titleRow.createCell(0);
            tc.setCellValue("Expense Intelligence – "+start.format(FMT)+" to "+end.format(FMT));
            tc.setCellStyle(titleStyle(wb));
            sheet.addMergedRegion(new CellRangeAddress(0,0,0,7)); row++;
            Row hRow = sheet.createRow(row++); hRow.setHeightInPoints(18);
            String[] cols = {"Title","Date","Category","AI Category","Amount","Currency","Payment","Merchant"};
            for (int i=0;i<cols.length;i++) { org.apache.poi.ss.usermodel.Cell c=hRow.createCell(i); c.setCellValue(cols[i]); c.setCellStyle(hStyle); }
            BigDecimal total = BigDecimal.ZERO;
            for (int i=0;i<expenses.size();i++) {
                Expense e = expenses.get(i); Row r = sheet.createRow(row++);
                CellStyle rs = i%2==0 ? normStyle : altStyle;
                setCell(r,0,e.getTitle(),rs); setCell(r,1,e.getExpenseDate().toString(),rs);
                setCell(r,2,e.getCategory()!=null?e.getCategory().getName():"Uncategorized",rs);
                setCell(r,3,e.getAiCategory()!=null?e.getAiCategory():"—",rs);
                org.apache.poi.ss.usermodel.Cell amt = r.createCell(4); amt.setCellValue(e.getAmount().doubleValue()); amt.setCellStyle(curStyle);
                setCell(r,5,e.getCurrency(),rs); setCell(r,6,e.getPaymentMethod()!=null?e.getPaymentMethod().name():"—",rs);
                setCell(r,7,e.getMerchant()!=null?e.getMerchant():"—",rs);
                total = total.add(e.getAmount());
            }
            row++; Row tr = sheet.createRow(row);
            org.apache.poi.ss.usermodel.Cell lbl = tr.createCell(3); lbl.setCellValue("TOTAL"); lbl.setCellStyle(totalStyle);
            org.apache.poi.ss.usermodel.Cell ta = tr.createCell(4); ta.setCellValue(total.doubleValue()); ta.setCellStyle(totalCurr);
            wb.write(baos); return baos.toByteArray();
        } catch (Exception e) { log.error("Excel failed",e); throw new RuntimeException("Excel generation failed",e); }
    }

    private CellStyle headerStyle(XSSFWorkbook wb) {
        CellStyle s=wb.createCellStyle(); XSSFFont f=wb.createFont(); f.setBold(true); f.setColor(IndexedColors.WHITE.getIndex()); f.setFontHeightInPoints((short)11); s.setFont(f);
        s.setFillForegroundColor(new XSSFColor(new byte[]{(byte)59,(byte)130,(byte)246},null)); s.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        s.setAlignment(HorizontalAlignment.CENTER); return s;
    }
    private CellStyle titleStyle(XSSFWorkbook wb) {
        CellStyle s=wb.createCellStyle(); XSSFFont f=wb.createFont(); f.setBold(true); f.setFontHeightInPoints((short)13); s.setFont(f); return s;
    }
    private CellStyle currencyStyle(XSSFWorkbook wb) {
        CellStyle s=wb.createCellStyle(); s.setDataFormat(wb.createDataFormat().getFormat("$#,##0.00")); s.setAlignment(HorizontalAlignment.RIGHT); return s;
    }
    private CellStyle altRowStyle(XSSFWorkbook wb) {
        CellStyle s=wb.createCellStyle(); s.setFillForegroundColor(new XSSFColor(new byte[]{(byte)248,(byte)250,(byte)252},null)); s.setFillPattern(FillPatternType.SOLID_FOREGROUND); return s;
    }
    private CellStyle totalStyle(XSSFWorkbook wb) {
        CellStyle s=wb.createCellStyle(); XSSFFont f=wb.createFont(); f.setBold(true); s.setFont(f); s.setAlignment(HorizontalAlignment.RIGHT); return s;
    }
    private CellStyle totalCurrStyle(XSSFWorkbook wb) {
        CellStyle s=wb.createCellStyle(); XSSFFont f=wb.createFont(); f.setBold(true); s.setFont(f); s.setDataFormat(wb.createDataFormat().getFormat("$#,##0.00")); s.setAlignment(HorizontalAlignment.RIGHT); return s;
    }
    private void setCell(Row r, int col, String val, CellStyle style) {
        org.apache.poi.ss.usermodel.Cell c=r.createCell(col); c.setCellValue(val); c.setCellStyle(style);
    }
}
